POST http://localhost:3000/signup
Content-Type: application/json

{
  
  "fullName": "ray",
  "email": "raymwebe@gmail.com",
  "phoneContact": "0755698485",
  "hostelName": "mmkkk boys",
  "password": "mwebe",
  "images":{
    "filename": "String",
      "path": "String",
  }
}



###
POST http://localhost:3000/booking
Content-Type: application/json

{
  "firstName": "Robin",
  "lastName": "Van",
  "email": "vanrobin@gmail.com",
  "phoneContact": "0755681485",
  "status": "pending"
}


###
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "raymwebe@gmail.com",
  "password": "mwebe"
 }



###
POST http://localhost:3000/hostellisting
Content-Type: application/json


{
  "buildingName": "Ruby",
  "location": "kk",
  "amenities": ["shuttle","reading room","cafeteria"],
  "roomsAvailable": "0",
  "rooms":  {
              "amount": 1000000,
              "capacity": "single",
              "type": "non self-contained"
            }
}


###
GET http://localhost:3000/search/hostels?page=1&limit=10&search=mysearch&type=self-contained&capacity=single&sort=buildingName,asc
Content-Type: application/json


###
GET http://localhost:3000/hostellisting/654367a4b0e980eeaf105ac5
Content-Type: application/json


###
GET http://localhost:3000/logout
Content-Type: application/json




###
PATCH  http://localhost:3000/hostellisting/654b51b396f46c189f3ff0bc
Content-Type: application/json

{
  "location": "kkk",
  "buildingName": "ruby complex"
 }

###
GET http://localhost:3000/view/654a1466b20babde565a700d
Content-Type: application/json

###
PATCH http://localhost:3000/update/654b525496f46c189f3ff0c3
Content-Type: application/json

{
  "lastName": "mark",
  "hostelName": "jinja hippo",
  "password": "king"
}


